# 라이브러리 로드

In [2]:
import pandas as pd
import numpy as np
import json
import os
from glob import glob

# 데이터 폴더 정리

### UrbanSound8K 데이터셋 Metadata
- `classID` : car_horn, dog_bark

In [4]:
metadata = pd.read_csv('data/UrbanSound8K/metadata.csv')
print(metadata.shape)
metadata.head()

(8732, 8)

,slice_file_name,fsID,start,end,salience,fold,classID,class
0,100032-3-0-0.wav,100032,0.0,0.317551,1,5,3,dog_bark
1,100263-2-0-117.wav,100263,58.5,62.500000,1,5,2,children_playing
2,100263-2-0-121.wav,100263,60.5,64.500000,1,5,2,children_playing
3,100263-2-0-126.wav,100263,63.0,67.000000,1,5,2,children_playing
4,100263-2-0-137.wav,100263,68.5,72.500000,1,5,2,children_playing

In [5]:
metadata['class'].value_counts()

class
dog_bark            1000
children_playing    1000
air_conditioner     1000
street_music        1000
jackhammer          1000
engine_idling       1000
drilling            1000
siren                929
car_horn             429
gun_shot             374
Name: count, dtype: int64

In [6]:
# 개 짖는 소리 (dog_bark), 자동차 경적 소리 (car_horn)만 필요
dog_bark = metadata[metadata['class'] == 'dog_bark']
car_horn = metadata[metadata['class'] == 'car_horn']

print(dog_bark.shape)
print(car_horn.shape)

(1000, 8)
(429, 8)

In [7]:
urban = pd.concat([car_horn[['slice_file_name', 'class', 'fold']], dog_bark[['slice_file_name', 'class', 'fold']]], ).rename(columns={'slice_file_name': 'file_name'}).reset_index(drop=True)
urban.head()

          file_name     class  fold
0  100648-1-0-0.wav  car_horn    10
1  100648-1-1-0.wav  car_horn    10
2  100648-1-2-0.wav  car_horn    10
3  100648-1-3-0.wav  car_horn    10
4  100648-1-4-0.wav  car_horn    10

### AI Hub 데이터셋 Metadata
- 대분류(`Division1`) : 알람
- 중분류(`Division2`) : 경보
- 소분류(`Class`) : 응급경보, 도난경보, 화재경보, 비상경보

#### 파일 정리
**기존** : data > AIHub > 1.Training > 라벨링데이터 > 1.응급경보 > S-210915_S_101_D_002_0001    
**변경** : data > AIHub > 1.Training > 라벨링데이터 > S-210915_S_101_D_002_0001

In [8]:
path = "./data/AIHub/"
dir1 = os.listdir(path)
dir2 = os.listdir(path + dir1[0])
dir3 = os.listdir(path + dir1[0] + '/' + dir2[0])
print(dir1)
print(dir2)
print(dir3)

['1.Training', '2.Validation']
['라벨링데이터', '원천데이터']

In [11]:
import shutil

# for d1 in dir1:
#     for d2 in dir2:
#         for d3 in dir3:
#             files = os.listdir(path + '/'.join([d1,d2,d3]))
#             for f in files:
#                 origin_path = path + '/'.join([d1,d2,d3,f])
#                 new_path = path + '/'.join([d1,d2,f])
#                 shutil.move(origin_path, new_path)

#### Metadata 가져오기

In [ ]:
# 경로 : dir1 > 라벨링데이터 > 파일명
# json 파일 미리보기
# "LabelDataInfo" - "Path" : 경로, "Desc" : 음성 종류
with open(path + dir1[0] + "/" + "라벨링데이터/S-210915_S_101_D_002_0001.json") as f:
    data = json.load(f)
    print(data)

{'RawDataInfo': {'RawDataId': 'S-210915_S_101_D_002', 'Copyrighter': '㈜미디어그룹사람과숲', 'SampleRate(Hz)': 44100, 'Channel': 1, 'BitDepth(bit)': 16, 'RecordingDevice': 'Android', 'BitRate(kbps)': 128, 'CollectionType': 'D', 'RecDateTime': '2021-09-15 18:50:46', 'RecDataLength(sec)': 28, 'Season': 'Fall', 'Weather': 'Sunny', 'TimeZone': 'Night', 'PlaceType': 'Outer', 'DistanceType': 'Near', 'FileExtension': 'mp3'}, 'SourceDataInfo': {'SourceDataId': 'S-210915_S_101_D_002_0001', 'FileExtension': 'mp3', 'NoOfClip': 1, 'ClipDataLength(sec)': 38}, 'LabelDataInfo': {'Path': 'S-210915_S_101_D_002', 'LabelID': 'S-210915_S_101_D_002_0001', 'NumAnnotator': 3, 'Division1': 'S', 'Division2': '1', 'Class': '01', 'Desc': '구급차 사이렌 소리', 'Type': 'SoundAnnotation', 'NumSegmentation': 1, 'Segmentations': [[9.95, 38.26]]}}

In [ ]:
# json 파일에서 Path와 Desc만 불러와서 데이터프레임으로

def file_to_df(path):
    fname = glob(path)
    file_name = []
    data_class = []
    for file in fname:
        with open(file, 'r') as f:
            data = json.load(f)
            file_name.append(data['LabelDataInfo']['LabelID'] + '.mp3')
            data_class.append(data['LabelDataInfo']['Desc'])
    df = pd.DataFrame({'file_name': file_name, 'class': data_class})
    return df

In [10]:
train_meta = file_to_df(path + dir1[0] + "/라벨링데이터/*")
valid_meta = file_to_df(path + dir1[1] + "/라벨링데이터/*")

aihub = pd.concat([train_meta, valid_meta])
print(aihub.shape)
aihub.head()

(679, 2)

                       file_name       class
0  S-210915_S_101_D_002_0001.mp3  구급차 사이렌 소리
1  S-211007_S_101_D_001_0001.mp3  구급차 사이렌 소리
2  S-211013_S_104_D_049_0001.mp3   자동차 경적 소리
3  S-211013_S_104_D_051_0001.mp3   자동차 경적 소리
4  S-211013_S_104_D_052_0001.mp3   자동차 경적 소리

In [ ]:
# 모든 음성 data/Train 폴더에

# # AIHub - 1.Training
# for f in list(train_meta['file_name']):
#     p = path + dir1[0] + '/원천데이터/'
#     shutil.move(p + f, "./data/Train")

# # AIHub - 2.Validation
# for f in list(valid_meta['file_name']):
#     p = path + dir1[1] + '/원천데이터/'
#     shutil.move(p + f, "./data/Train")

# # UrbanSound8k
# for fold, file in zip(urban['fold'], urban['file_name']):
#     origin_path = f'./data/UrbanSound8K/audio/fold{str(fold)}/{file}'
#     shutil.move(origin_path, "./data/Train")

## Metadata 데이터프레임 합치기

In [12]:
urban.head()

          file_name     class  fold
0  100648-1-0-0.wav  car_horn    10
1  100648-1-1-0.wav  car_horn    10
2  100648-1-2-0.wav  car_horn    10
3  100648-1-3-0.wav  car_horn    10
4  100648-1-4-0.wav  car_horn    10

In [13]:
aihub.head()

                       file_name       class
0  S-210915_S_101_D_002_0001.mp3  구급차 사이렌 소리
1  S-211007_S_101_D_001_0001.mp3  구급차 사이렌 소리
2  S-211013_S_104_D_049_0001.mp3   자동차 경적 소리
3  S-211013_S_104_D_051_0001.mp3   자동차 경적 소리
4  S-211013_S_104_D_052_0001.mp3   자동차 경적 소리

In [32]:
file_names = pd.concat([urban[['file_name', 'class']], aihub]).reset_index(drop=True)
file_names.head(10)

          file_name     class
0  100648-1-0-0.wav  car_horn
1  100648-1-1-0.wav  car_horn
2  100648-1-2-0.wav  car_horn
3  100648-1-3-0.wav  car_horn
4  100648-1-4-0.wav  car_horn
5  107090-1-0-0.wav  car_horn
6  107090-1-1-0.wav  car_horn
7  117536-1-0-0.wav  car_horn
8  118070-1-0-0.wav  car_horn
9  118496-1-0-0.wav  car_horn

In [33]:
file_names.shape

(2108, 2)

In [34]:
file_names['class'].value_counts()

class
dog_bark               1000
car_horn                429
자동차 경적 소리               134
화재경보 소리                 129
도난경보 소리                 121
응급경보 소리                  66
화재 경보 소리                 57
비상경보 소리                  54
침입감지 경보 소리               21
민방위훈련 사이렌 소리             16
경찰차 사이렌 소리               13
소방차 사이렌 소리               11
구급차 사이렌 소리               11
공습경보 소리                  10
도난 경보음 소리                 9
가스누설 화재경보 소리              7
렉카차 사이렌 소리                5
경찰차 사이렌                   5
철도 건널목 신호음 소리             3
전주 완산 소방서 화제 사이렌 소리       2
응급경보 사이렌 소리               1
소방서 구급 경보 사이렌 소리          1
소방서 경찰 순찰차 사이렌 소리         1
재난경보 소리                   1
해안 경찰 보트 사이렌 소리           1
Name: count, dtype: int64

### 필요 없는 클래스 제거

In [35]:
print(file_names['class'].unique())

['car_horn' 'dog_bark' '구급차 사이렌 소리' '자동차 경적 소리' '경찰차 사이렌 소리' '화재경보 소리'
 '화재 경보 소리' '비상경보 소리' '철도 건널목 신호음 소리' '소방차 사이렌 소리' '응급경보 소리' '렉카차 사이렌 소리'
 '도난경보 소리' '가스누설 화재경보 소리' '응급경보 사이렌 소리' '민방위훈련 사이렌 소리' '소방서 구급 경보 사이렌 소리'
 '소방서 경찰 순찰차 사이렌 소리' '전주 완산 소방서 화제 사이렌 소리' '도난 경보음 소리' '침입감지 경보 소리'
 '공습경보 소리' '경찰차 사이렌' '재난경보 소리' '해안 경찰 보트 사이렌 소리']

- car_horn = 자동차 경적 소리 
- dog_bark -> 개 짖는 소리
- 경찰차 사이렌 소리 = **경찰차 사이렌**
- **소방차 사이렌** 소리 = 전주 완산 소방서 화제 사이렌 소리
- **응급경보** 소리 = 응급경보 사이렌 소리 ??
- **구급차 사이렌** 소리
- **화재경보** 소리 = 화재 경보 소리
- **도난경보** 소리 = 도난 경보음 소리
- **가스누설 화재경보** 소리
- 침입감지 경보 소리 -> **침입 경보**
- **공습경보** 소리
    
삭제할 소리    
  - ~~비상경보 소리~~ : 여러 경보음 섞여있음
  - ~~철도 건널목 신호음 소리~~ : 필요도 없고, 3개 밖에 없음
  - ~~렉카차 사이렌 소리~~ : 필요없음
  - ~~민방위훈련 사이렌 소리~~ : 필요 없음 
  - ~~소방서 구급 경보 사이렌 소리~~ : 1개 밖에 없음
  - ~~소방서 경찰 순찰차 사이렌 소리~~ : 1개 밖에 없음
  - ~~재난경보 소리~~ : 1개 밖에 없음
  - ~~해안 경찰 보트 사이렌 소리~~ : 1개 밖에 없음

In [36]:
# class 값 수정
file_names.replace({'car_horn':'자동차 경적'}, inplace=True)
file_names.replace({'자동차 경적 소리':'자동차 경적'}, inplace=True)

file_names.replace({'dog_bark':'개 짖는 소리'}, inplace=True)

file_names.replace({'경찰차 사이렌 소리':'경찰차 사이렌'}, inplace=True)

file_names.replace({'소방차 사이렌 소리':'소방차 사이렌'}, inplace=True)
file_names.replace({'전주 완산 소방서 화제 사이렌 소리':'소방차 사이렌'}, inplace=True)

file_names.replace({'응급경보 소리':'응급 경보'}, inplace=True)
file_names.replace({'응급경보 사이렌 소리':'응급 경보'}, inplace=True)

file_names.replace({'구급차 사이렌 소리':'구급차 사이렌'}, inplace=True)

file_names.replace({'화재경보 소리':'화재 경보'}, inplace=True)
file_names.replace({'화재 경보 소리':'화재 경보'}, inplace=True)

file_names.replace({'도난경보 소리':'도난 경보'}, inplace=True)
file_names.replace({'도난 경보음 소리':'도난 경보'}, inplace=True)

file_names.replace({'가스누설 화재경보 소리':'가스누설 화재 경보'}, inplace=True)

file_names.replace({'침입감지 경보 소리':'침입 경보'}, inplace=True)

file_names.replace({'공습경보 소리':'공습 경보'}, inplace=True)

In [37]:
file_names['class'].value_counts()

class
개 짖는 소리              1000
자동차 경적                563
화재 경보                 186
도난 경보                 130
응급 경보                  67
비상경보 소리                54
침입 경보                  21
경찰차 사이렌                18
민방위훈련 사이렌 소리           16
소방차 사이렌                13
구급차 사이렌                11
공습 경보                  10
가스누설 화재 경보              7
렉카차 사이렌 소리              5
철도 건널목 신호음 소리           3
소방서 경찰 순찰차 사이렌 소리       1
소방서 구급 경보 사이렌 소리        1
재난경보 소리                 1
해안 경찰 보트 사이렌 소리         1
Name: count, dtype: int64

In [38]:
# 위험소리가 아니거나 데이터 수가 1개인 경우 제거
drop_class = ['비상경보 소리', '철도 건널목 신호음 소리', '렉카차 사이렌 소리', '민방위훈련 사이렌 소리', '소방서 구급 경보 사이렌 소리', '소방서 경찰 순찰차 사이렌 소리', '재난경보 소리', '해안 경찰 보트 사이렌 소리']
file_names = file_names[~file_names['class'].isin(drop_class)]

file_names['class'].value_counts()

class
개 짖는 소리       1000
자동차 경적         563
화재 경보          186
도난 경보          130
응급 경보           67
침입 경보           21
경찰차 사이렌         18
소방차 사이렌         13
구급차 사이렌         11
공습 경보           10
가스누설 화재 경보       7
Name: count, dtype: int64

In [4]:
file_names.shape

(2026, 2)

### label 숫자 인코딩

In [8]:
file_names.sample(5)

                          file_name    class
1742  S-211103_S_102_C_287_0001.mp3    도난 경보
1884  S-211116_S_104_C_012_0001.mp3   자동차 경적
998                 29936-3-1-0.wav  개 짖는 소리
941                207124-3-0-0.wav  개 짖는 소리
698                164312-3-1-0.wav  개 짖는 소리

In [9]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

file_names['class_num'] = encoder.fit_transform(file_names['class'])
file_names.head()

          file_name   class  class_num
0  100648-1-0-0.wav  자동차 경적          8
1  100648-1-1-0.wav  자동차 경적          8
2  100648-1-2-0.wav  자동차 경적          8
3  100648-1-3-0.wav  자동차 경적          8
4  100648-1-4-0.wav  자동차 경적          8

In [18]:
classes = file_names[['class', 'class_num']].sort_values('class_num').drop_duplicates(ignore_index=True)
classes

         class  class_num
0   가스누설 화재 경보          0
1      개 짖는 소리          1
2      경찰차 사이렌          2
3        공습 경보          3
4      구급차 사이렌          4
5        도난 경보          5
6      소방차 사이렌          6
7        응급 경보          7
8       자동차 경적          8
9        침입 경보          9
10       화재 경보         10

파일로 저장

In [19]:
file_names.to_csv('./data/file_names.csv', index=False)
classes.to_csv('./data/classes.csv', index=False)